//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacakBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCards
    {
        public int ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string CardNumber { get; set; }
        public string expMonth { get; set; }
        public string expYear { get; set; }
        public string CVVNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
