//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacakBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KacakBank_DBEntities : DbContext
    {
        public KacakBank_DBEntities()
            : base("name=KacakBank_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerCards> CustomerCards { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<POSMerchants> POSMerchants { get; set; }
    }
}
