//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KacakBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMerchants
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string MerchantCode { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
